#!/usr/bin/env node

let cheerio = require('cheerio')
let fs = require('fs')

let raw = fs.readFileSync('/dev/stdin').toString()
    .replace(/<(xa|nota|ax)\b/g, '<a')    // fix random junk
    .replace(/<ximg\b/g, '<img')
let $ = cheerio.load(raw)

let title = $('title').text()
let body = $($('table')[1])

body.find('font').removeAttr('color').removeAttr('size').removeAttr('face')

let comment = body.find('i').first()
if (comment.text().trim()[0] === '(') comment.wrap('<aside class="part">')

body.find('img[src*="yimg.com"]').remove()
body.find('img[src*="virtumundo.com"]').remove()

body = body.html().replace(/<br><br>/g, '</p><p>')
    // separate the article text form the notes
    .replace(/<p>\s*?<b>Notes:?<\/b><\/p>/g, '</div>$&')
    .replace(/<p>\s*?<b>([^<>]+)<\/b><\/p>/g, '<h3>$1</h3>')

let html = `<!doctype html>
<meta charset="utf-8">
<title>${title}</title>
<meta name="author" content="Paul Graham">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  div p { margin: 0; padding: 0; }
  div p + p { text-indent: 2em; }
  .part,center { margin: 1em 0; }
</style>

<h2 class="title">${title}</h2>

<div><p>${body}</p>`

// get date
$ = cheerio.load(html)
let re = /^\s*(January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{4}\s*$/
$('p').each( (_,v) => {
    let text = $(v).text()
    if (re.test(text)) {
        return !$(v).replaceWith(`<div class="part"><time datetime=${new Date().toISOString()}>${text}</time></div>`)
    }
})

process.stdout.write($.html())
